---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)
```

```{r}
data("rest_inspec")

rest_inspec = 
  rest_inspec %>%
  select(
    boro, critical_flag, building, cuisine_description, 
    inspection_date,score, zipcode, grade) %>%
  filter(
    boro == "MANHATTAN",
    critical_flag == "Not Critical",
    cuisine_description %in% c("American", "Chinese", "Italian",	
"Mexican", "Japanese", "Spanish", "Caribbean"),
    inspection_date < '2015-01-01',
    score < 28,
  ) %>%
  drop_na(grade)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Relationship between Cuisine Type, Inspection Score (<28). and Grade (A, B, C, P) of the Non-Critical Restaurants in Manhattan

```{r}
rest_inspec %>%
  mutate(text_label = str_c("grade: ", grade)) %>%
  plot_ly(
    x = ~cuisine_description, y = ~score, color = ~grade, 
    text = ~text_label, alpha = 0.5, 
    type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### The Distribution of Inspection Score in Each Cuisine Type in Manhattan

```{r}
rest_inspec %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
  plot_ly(
    y = ~score, x = ~cuisine_description, 
    color = ~cuisine_description,
    type = "box", colors = "viridis")
```

### The Number of Non-Critical Restaurants in Each Cuisine Type in Manhattan

```{r}
rest_inspec %>%
  count(cuisine_description) %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>%
  plot_ly(
    x = ~cuisine_description, y = ~n, color = ~cuisine_description, 
    type = "bar", colors = "viridis")
```

